export enum Routes {
  HOME = '/',
  LOGIN = '/prihlaseni',
  LEAGUES = '/ligy',
  LEAGUES_OVERVIEW = '/mix-ligy',
  STATISTICS = '/statistiky',
  SEASON_DETAIL = '/detail-sezona/:id',
  SEASON_CREATE = '/vytvoreni-sezony',
  SEASON_UPDATE = '/uprava-sezony/:id',
  MIXED_MATCH_CREATE = '/vytvoreni-mix-zapasu/:id',
  MIXED_MATCH_DETAIL = '/detail-mix-zapasu/:id',
  MIXED_MATCH_UPDATE = '/uprava-mix-zapasu/:id',
  MIXED_MATCH_RESULT = '/zadat-vysledek-mix-zapasu/:id',
  // TEAMS
  TEAM_CREATE = '/vytvoreni-tymu',
  TEAM_UPDATE = '/uprava-tymu/:id',
  TEAM_DETAIL = '/tym/:id',
  // USERS
  REGISTRATION = '/registrace',
  USER = '/uzivatel',
  MCRVC = '/mcrvc',
  HALLOFFAME = '/sin-slavy',
  CONTACT = '/kontakty',
  LOGOUT = '/odhlaseni',
  REGISTRATION_SUCCESS = '/uspesna-registrace',
  EDIT_PROFILE = '/edit-profile',
}
