export enum LeagueEndpoints {
  LEAGUES = '/leagues',
  LEAGUE_SEASONS = '/leagues/{id}/seasons',
  SEASON_DETAIL = '/seasons/{seasonId}',
  MAPS_IN_SEASON = '/seasons/{seasonId}/maps',
  LADDER_LIST = '/seasons/{seasonId}/ladder',
  SEASON_TEAM_LIST = '/seasons/{seasonId}/teams',
  MATCH_LIST = '/seasons/{seasonId}/matches',
  CREATE_MATCH_CHALLENGE = '/seasons/{seasonId}/create-match-challenge',
  ACCEPT_MATCH_CHALLENGE = '/matches/{matchId}/accept-match-challenge',
  REJECT_MATCH_CHALLENGE = '/matches/{matchId}/reject-match-challenge',
  SET_MATCH_SCORE = '/matches/{matchId}/set-match-score',
  UPDATE_MATCH_STATUS = '/matches/{matchId}/update-status',
  CONFIRM_MATCH_SCORE = '/matches/{matchId}/confirm-match-score',
  MATCH_BY_ID = '/matches/{matchId}',
  EXPECTED_ELO_POINTS = '/matches/expected-elo-points/{challengerId}/{opponentId}',
  ROUNDS_SCREENSHOT_UPLOAD = '/matches/{matchId}/rounds/{roundId}/screenshot-upload-url',
  REMOVE_ROUND_SCREENSHOT = '/match-rounds/{roundId}/remove-screenshot',
  MATCH_COMMENT = '/matches/{matchId}/comments',
  CREATE_ROUND = '/matches/{matchId}/match-rounds',
  SORT_ROUNDS = '/matches/{matchId}/sort-rounds',
  ROUND_BY_ID = '/match-rounds/{roundId}',
  RECALCULATE_PLAYER_STATS = '/matches/{matchId}/recalculate-match-player-stats',
  JOIN_SEASON = '/seasons/{seasonId}/join-team/{teamId}',
  TOP_PLAYERS_OF_DAY = '/seasons/{seasonId}/top-players-of-the-day/{date}',
  FILES_FOR_MATCH_SCORE_LIST = '/matches/{matchId}/show-score-files-available-for-match',
  RECALCULATE_MATCH_SCORE_BY_FILE = '/matches/files/{fileId}/recalculate-round-match-score',
}
