export enum Nation {
  US = 'US',
  VC = 'VC',
}

export enum PlayersCount {
  FOUR = 'FOUR',
  FIVE = 'FIVE',
  SIX = 'SIX',
  SEVEN = 'SEVEN',
  EIGHT = 'EIGHT',
  NINE = 'NINE',
  TEN = 'TEN',
}

export enum LeagueType {
  TEAMPLAY = 'TEAMPLAY',
}

export enum SeasonStatus {
  NEW = 'NEW',
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum MatchStatus {
  NEW = 'NEW',
  ACCEPTED = 'ACCEPTED',
  REJECTED_BY_CHALLENGER = 'REJECTED_BY_CHALLENGER',
  REJECTED_BY_OPPONENT = 'REJECTED_BY_OPPONENT',
  REJECTED_BY_ADMIN = 'REJECTED_BY_ADMIN',
  WAITING_FOR_CONFIRMATION = 'WAITING_FOR_CONFIRMATION',
  WAITING_FOR_SCORE_CONFIRMATION = 'WAITING_FOR_SCORE_CONFIRMATION',
  COMPLAINT = 'COMPLAINT',
  FINISHED = 'FINISHED',
}
