export enum BeErrors {
  INVALID_MATCH_STATUS = 'INVALID_MATCH_STATUS',
  MATCH_STATUS_IS_NOT_NEW = 'MATCH_STATUS_IS_NOT_NEW',
  SEASON_STATUS_IS_NOT_NEW = 'SEASON_STATUS_IS_NOT_NEW',
  SEASON_STATUS_IS_NOT_ACTIVE = 'SEASON_STATUS_IS_NOT_ACTIVE',
}
