export const players = [
  {
    id: 'playerId1',
    name: 'Trapper',
    played: 5,
    kills: 471,
    flags: 9,
    deaths: 286,
    points: 107,
  },
  {
    id: 'playerId2',
    name: 'Bascci ze Sapy',
    played: 4,
    kills: 428,
    flags: 3,
    deaths: 230,
    points: 106,
  },
  {
    id: 'playerId3',
    name: 'Crashy',
    played: 3,
    kills: 272,
    flags: 7,
    deaths: 151,
    points: 97,
  },
  {
    id: 'playerId4',
    name: 'Fronty zabugovanec',
    played: 4,
    kills: 284,
    flags: 3,
    deaths: 204,
    points: 95,
  },
  {
    id: 'playerId5',
    name: 'Buqalow',
    played: 6,
    kills: 567,
    flags: 5,
    deaths: 347,
    points: 84,
  },
];
